-- AlterTable
ALTER TABLE `Event` MODIFY `createAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `User` MODIFY `role` ENUM('ORGANIZER', 'ATTENDEE') NOT NULL DEFAULT 'ATTENDEE';
